name: generate

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  # Generate schemas from elastic/package-spec@v* and commit changes.
  generate-tags:
    permissions:
      # Allow job to write to a branch and open a PR.
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: .generate/go.sum

      - uses: sourcemeta/jsonschema@v11.5.0
      - uses: extractions/setup-just@v3

      - name: generate
        run: just all
        working-directory: .generate

      - name: check for modified versions
        id: is-changed
        run: echo "modified=$(if git status --porcelain | grep -q -P '\d+\.\d+\.\d+'; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT

      - name: timestamp
        id: timestamp
        run: echo "timestamp=$(date +"%Y-%m-%dT%H:%M:%S%z")" >> $GITHUB_OUTPUT

      - name: Create PR
        if: steps.is-changed.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            elastic/package-spec @${{ steps.timestamp.outputs.timestamp }} update
            
            Update code based on https://github.com/elastic/package-spec.
          title: elastic/package-spec @${{ steps.timestamp.outputs.timestamp }} update
          body: Update code based on Update code based on https://github.com/elastic/package-spec.
          base: main
          labels: automation
          branch: package-spec-update
          delete-branch: true

  # Generate schemas from elastic/package-spec@main
  generate-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: .generate/go.sum

      - uses: sourcemeta/jsonschema@v11.5.0
      - uses: extractions/setup-just@v3

      - name: generate
        run: just generate main
        working-directory: .generate
